### ISSUE TITLE
Modulous errors when trying to overwrite a file

### ISSUE THREAD

**Issue by DismalAmoeba** [ModulousSmash/ModulousMM#4]
Happens when I try to overwrite a mod zip file. Nothing changes in the original.

*************\* Exception Text **************
System.IO.IOException: The file 'C:\Users\DismalAmoeba\Desktop\younglink.zip' already exists.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.Compression.ZipFile.Open(String archiveFileName, ZipArchiveMode mode, Encoding entryNameEncoding)
   at System.IO.Compression.ZipFile.DoCreateFromDirectory(String sourceDirectoryName, String destinationArchiveFileName, Nullable`1 compressionLevel, Boolean includeBaseDirectory, Encoding entryNameEncoding)
   at ModulousMM.ModCreateForm.save_button_Click(Object sender, EventArgs e) in c:\Users\ALEX\Documents\Visual Studio 2013\Projects\ModulousLib\ModulousMM\ModCreateForm.cs:line 125
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

*************\* Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.5.27.0 built by: FX453PREVIEWREL
##     CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll

ModulousMM
    Assembly Version: 0.9.5655.2472
    Win32 Version: 0.9.5655.2472
##     CodeBase: file:///C:/Users/DismalAmoeba/Desktop/Modulous%20Mod%20Manager%20(1)/ModulousMM.exe

System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.5.27.0 built by: FX453PREVIEWREL
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll

System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.5.27.0 built by: FX453PREVIEWREL
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll

System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.5.27.0 built by: FX453PREVIEWREL
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll

XDMessaging
    Assembly Version: 4.0.9.0
    Win32 Version: 4.0.9
##     CodeBase: file:///C:/Users/DismalAmoeba/Desktop/Modulous%20Mod%20Manager%20(1)/XDMessaging.DLL

ModulousLib
    Assembly Version: 0.9.5655.2242
    Win32 Version: 0.9.5655.2242
##     CodeBase: file:///C:/Users/DismalAmoeba/Desktop/Modulous%20Mod%20Manager%20(1)/ModulousLib.DLL

System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.5.27.0 built by: FX453PREVIEWREL
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll

System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.5.27.0 built by: FX453PREVIEWREL
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

NLua
    Assembly Version: 1.3.2.0
    Win32 Version: 1.3.2
##     CodeBase: file:///C:/Users/DismalAmoeba/Desktop/Modulous%20Mod%20Manager%20(1)/NLua.DLL

KeraLua
    Assembly Version: 1.3.2.0
    Win32 Version: 1.3.2.0
##     CodeBase: file:///C:/Users/DismalAmoeba/Desktop/Modulous%20Mod%20Manager%20(1)/KeraLua.DLL

Newtonsoft.Json
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.8.18111
##     CodeBase: file:///C:/Users/DismalAmoeba/Desktop/Modulous%20Mod%20Manager%20(1)/Newtonsoft.Json.DLL

System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.5.27.0 built by: FX453PREVIEWREL
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll

System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.5.27.0 built by: FX453PREVIEWREL
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll

System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.5.27.0 built by: FX453PREVIEWREL
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll

System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.5.27.0 built by: FX453PREVIEWREL
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll

System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.5.27.0 built by: FX453PREVIEWREL
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll

XDMessaging.Transport.Amazon
    Assembly Version: 4.0.9.0
    Win32 Version: 4.0.9
##     CodeBase: file:///C:/Users/DismalAmoeba/Desktop/Modulous%20Mod%20Manager%20(1)/XDMessaging.Transport.Amazon.DLL

XDMessaging.Transport.IOStream
    Assembly Version: 4.0.9.0
    Win32 Version: 4.0.9

**Comment by EIREXE** [comment]
Fixed in 990e68b5c39633fd60154b16389ccdc8bd8db3ae
